version : "3.7"
services :
  monolito :
    container_name : monolito
    image : monolito:v1
    build : 
      context : .
    ports : 
      - "4001:4001"
    networks : 
     - proyectos-app
    environment:
      MONGO_URI: ${MONGO_URI}

networks : 
  proyectos-app :